services:
  vote:
    build: ./vote
    ports:
      - "80:80"
    depends_on:
      - redis
  result:
    build: ./result
    ports:
      - "8080:80"

  redis:
    image: redis:alpine
    depends_on:
      - worker
  worker:
    build: ./worker
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - result